### ISSUE TITLE
rm -rf * please

### ISSUE THREAD

**Issue by benedfit** [letsgetrandy/DICSS#17]

**Comment by allypalanzi** [comment]
+1

**Comment by Nijikokun** [comment]
:-1:

**Comment by ghost** [comment]
Are you telling @letsgetrandy to kill himself? How would it feel if someone told that to yourself?

**Comment by LegoStormtroopr** [comment]
If you don't like DICCS don't install it. The documentation clearly states:

> While we believe most people are fond of DICSS, we realize that DICSS isn't for everyone. There are plenty of alternatives. Feel free to use them instead. And please, never force someone to use DICSS if they're not willing.

**Comment by ecnepsnai** [comment]
Oh no! A guy made JavaScript library that **triggered** me!

**Comment by WaveringAna** [comment]
On what, rm -rf will just delete everything in the folder it is in

**Comment by ghost** [comment]
>2015
>not using sudo rm -rf / --no-preserve-root

Stay pleb

**Comment by kbradsha** [comment]
Benefdt please just die in a fire. People like you give social justice warriors the condescending stereotype they currently have. Have you no understanding of the freedom of speech? HINT: it's not just for popular speech ass!
