### ISSUE TITLE
Happy 420!!!

### ISSUE THREAD

**Issue by Operation420** [letsgetrandy/DICSS#56]
Sorry I am a day late.

HAPPY 420 legalize it!!!

**Comment by Operation420** [comment]
Why closed?

**Comment by letsgetrandy** [comment]
Unrelated.

**Comment by Operation420** [comment]
Fair enough.

So you're not a propogandist dick or anything, just coz not related?

**Comment by letsgetrandy** [comment]
Correct. "Happy 420" in not related to DICSS.

**Comment by Operation420** [comment]
I hate prohibitionist DICSS lol

**Comment by letsgetrandy** [comment]
Hahaha
